import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "../redux/Providers"; // ✅ Use your client wrapper
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TalentBridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Use Providers instead of react-redux Provider directly */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
