# -*- coding: utf-8 -*-
"""TalentBridge-similarity-model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1th7ixx4JkzbVhbMcN-b1qsve_HT1VU90
"""

# Installer les dépendances
!pip install scikit-learn pandas --quiet

# Monter Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Importer les bibliothèques
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

# Charger le dataset
CSV_PATH = "/content/drive/MyDrive/questions.csv"
df = pd.read_csv(CSV_PATH)
df = df.dropna(subset=['question1', 'question2', 'is_duplicate'])
df = df[df['is_duplicate'].isin([0, 1])]

# Prétraitement : Combiner les questions et calculer la similarité cosinus
vectorizer = TfidfVectorizer(stop_words='english', max_features=10000)
combined_questions = df['question1'] + ' ' + df['question2']
tfidf_matrix = vectorizer.fit_transform(combined_questions)

# Calculer la similarité cosinus (ou utiliser comme feature)
# Pour simplicité, utilisons la similarité cosinus comme feature unique
similarities = []
for i in range(len(df)):
    vec1 = vectorizer.transform([df.iloc[i]['question1']])
    vec2 = vectorizer.transform([df.iloc[i]['question2']])
    sim = cosine_similarity(vec1, vec2)[0][0]
    similarities.append(sim)

df['similarity'] = similarities

# Features et labels
X = df[['similarity']]  # Ou utilise tfidf_matrix directement pour plus de features
y = df['is_duplicate']

# Split train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Modèle
model = RandomForestClassifier(n_estimators=50, random_state=42)
model.fit(X_train, y_train)

# Prédictions et évaluation
predictions = model.predict(X_test)
auc = roc_auc_score(y_test, predictions)
print(f"AUC sur le test set: {auc}")

# Sauvegarder le modèle
import joblib
joblib.dump(model, '/content/drive/MyDrive/quora_similarity_sklearn_model.pkl')
print("Modèle sauvegardé.")